### ISSUE TITLE
add all playbooks needed into provision-all.yml

### ISSUE THREAD

**Issue by ikke-t** [mglantz/ansible-roadshow#13]
There is the provision-all playbook that should do it all in one playbook run. I added instance creation and gitlab install while I tried gitlab part. Make sure all parts are included. Still missing at least:

1. tower install
2. lab machines configs
3. gitlab add users and import project.

**Comment by ikke-t** [comment]
this file: https://github.com/mglantz/ansible-roadshow/blob/master/content/provision-all.yml

**Comment by pgustafs** [comment]
tower install and lab machines configs should not be added to the provision-all playbook, they are executed as user_data script on instance deployment.

**Comment by mglantz** [comment]
Fixed then, reopen if you are not happy about that @ikke-t

**Comment by ikke-t** [comment]
Where did you fix it? I don't see commmit
