### ISSUE TITLE
Disable public key authentication method for Ansible tower

### ISSUE THREAD

**Issue by peerster** [mglantz/ansible-roadshow#131]
It seems that if you have many ssh keys that your ssh client is trying to use when you try to login to Ansible tower server, you can get the `Too many authentication failures` and not being able to login.
One solution would be to turn off that method in the sshd_config on the server.

**Comment by mglantz** [comment]
Thanks for suggesting this :) We are considering some different ways of preventing people of hammering the systems. Changing default port seems like the most minimal change with least impact atm, or changing AWS network security policies.

**Comment by mglantz** [comment]
We are using key authentication for setup / confirmation of the lab, so we cannot turn off the method.

**Comment by peerster** [comment]
Maybe increase `MaxAuthTries` could mitigate this, but then you will increase the chance of brute Force I guess
