### ISSUE TITLE
Lab 5 will leave the vault password in the bash history

### ISSUE THREAD

**Issue by theNaughtyOtter** [mglantz/ansible-roadshow#145]
echo “mypass123” >$WORK_DIR/mypassword

Will remain in the bash history - the instructions should be updated to ensure security (after all, this lab is on security!)

Either 
1) after the command history -d <offset> 
Or
2) use an editor to edit the $WORK_DIR/mypassword file with the password

**Comment by mglantz** [comment]
Using an editor to edit the file seems like the way forward 👍 Feel free to create a pull request for the changes.

**Comment by bentterp** [comment]
just put a space in front of the command so it wont be put in history

**Comment by theNaughtyOtter** [comment]
multiple solutions :) i favored including history -d as it’s a solution for just in case you forget to use the alternates which must be done before
