### ISSUE TITLE
LAB4: Edit $WORK_DIR/lb.yml to include the newly created role

### ISSUE THREAD

**Issue by danost84** [mglantz/ansible-roadshow#146]
Edit $WORK_DIR/lb.yml to include the newly created role:

---
- name: Install and configure NGINX as a load balancer
  hosts: lbservers
  become: true
  tasks:
  - include_role:
      name: nginxinc.nginx
  - include_role:
      name: nginx-config

When incloude the lines abow: which give file:
lb.yml:
---
- name: Install NGNIX
  hosts: lbservers
  become: true
  tasks:
  - include_role:
      name: nginxinc.nginx
---
- name: Install and configure NGINX as a load balancer
  hosts: lbservers
  become: true
  tasks:
  - include_role:
      name: nginxinc.nginx
  - include_role:
      name: nginx-config

when run the playbook:
[student@ip-172-31-31-10 work]$ ansible-playbook -i hosts lb.yml
ERROR! Syntax Error while loading YAML.
  but found another document

The error appears to have been in '/home/student/work/lb.yml': line 8, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      name: nginxinc.nginx
---
^ here

Discription should be:
Edit $WORK_DIR/lb.yml to replace text in the newly created role:
Ass --- is added when in start of a playbook, two --- will create the error

---
- name: Install and configure NGINX as a load balancer
  hosts: lbservers
  become: true
  tasks:
  - include_role:
      name: nginxinc.nginx
  - include_role:
      name: nginx-config

**Comment by mglantz** [comment]
I've made a fix to the lab making it more clear if it's a matter of appending things or not.  Fixed in 0ef1690  
Does that solve things for you?

**Comment by mglantz** [comment]
I'm closing this. Feel free to re-open if you don't think it was resolved properly.
