### ISSUE TITLE
Lab 9: connection from Tower server to Ansible lost

### ISSUE THREAD

**Issue by jacobborella** [mglantz/ansible-roadshow#52]
I can't see logs or status of workflows in the Tower console when I start a new job.

**Comment by mglantz** [comment]
Possible fix in  986da3b

**Comment by mglantz** [comment]
BASE_URL needs to be changed to the proper one. We'll add instructions on how to do this using the GUI. Does not seem to be doable via the CLI or by manipulating the database directly.

**Comment by jacobborella** [comment]
What about using: https://docs.ansible.com/ansible-tower/latest/html/userguide/notifications.html#resetting-the-tower-url-base

"In /etc/tower/settings.py, you can modify TOWER_URL_BASE='https://tower.example.com'; to change the notification hostname, replacing https://tower.example.com with your preferred hostname. You must restart Tower services after saving your changes with ansible-tower-service restart."

**Comment by jacobborella** [comment]
For completeness:
"17.5.1. Resetting the TOWER_URL_BASE
The primary way that Tower determines how the base URL (TOWER_URL_BASE) is defined is by looking at an incoming request and setting the server address based on that incoming request.

Tower takes settings values from the database first. If no settings values are found, Tower falls back to using the values from the settings files. If a user posts a license by navigating to the Tower host’s IP adddress, the posted license is written to the settings entry in the database."

**Comment by ikke-t** [comment]
If you add that, there is already made ansible lineinfile command in "ignore invalid ssl certs" ticket. Just add thus line too. I didn't have chance to apply the fix and test it.

**Comment by mglantz** [comment]
It doesn't work @ikke-t, we have to introduce manual instructions, me and @teemu-u worked on that issue for 2 hours atleast. Modified database directly, tried to reset values.. and so on.

**Comment by mglantz** [comment]
Fixed, instructions in lab 7 added

**Comment by mglantz** [comment]
OK, we now have a proper solution for this. We're no longer reading back a backup, but registering a subscription on the fly at the end of the install. When doing this against the public IP (which we fetch from AWS API) the base_url get's properly set. So, yeah. Problem properly solved, thanks for @pgustafs who figured out the insides of Towers undocumented API features.
