### ISSUE TITLE
document tower install into infra setup README

### ISSUE THREAD

**Issue by ikke-t** [mglantz/ansible-roadshow#74]
Tower installation guide is missing from content/README.md

**Comment by mglantz** [comment]
Not needed AFAIK, it's all automated.. re-open it if you don't agree :)

**Comment by ikke-t** [comment]
I'd add oneliner saying the parameters to ansible commands. For some reason this is not enabled as part of provision-all.yml. So it needs separate command, and thus should be listed in content/README.md. Or better yet, added to main playbook provision-all.yml which is already instructed.

**Comment by pgustafs** [comment]
If the tower install playbook is added to provision-all playbook the installation time for very large demo setups would be considerably longer, so I think it is best to keep as is.

**Comment by ikke-t** [comment]
Then it would be good to have the necessary commabds added to README. About the time, is it faster done some other way, and could it get done similarly combined?

**Comment by mglantz** [comment]
Solved in ab62f13
