### ISSUE TITLE
Lab 8 can't be finished at the moment

### ISSUE THREAD

**Issue by jacobborella** [mglantz/ansible-roadshow#87]
Lab 8 assumes the user has created a git repo with all code, which exists in $WORK_DIR. This hasn't been done during lab 6 or 7, since those steps manually create a repo with a ping playbook.

I suggest we keep the instructions on creating a git repo in lab 6, but then add everything from $WORK_DIR by doing the following steps:
```
cd $WORK_DIR
echo "Ansible Workshop" > README.md
git init .
git commit -m "first commit"
git remote add origin <your git url>
git push -u origin master
```

**Comment by mglantz** [comment]
Fixed in 8e5a463
